# travis rules for project
language: cpp
compiler:
  - gcc

before_install:
  # install deps
  - sudo apt-get install -y cmake libopencv-dev gl-dev freeglut3-dev libxmu-dev

script: # compile
  - mkdir build
  - cd build
  - cmake ..
  - make
